{
 "cells": [
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [],
   "source": [
    "import math\n",
    "import gc\n",
    "import numpy as np\n",
    "import pandas as pd\n",
    "from matplotlib import pyplot\n",
    "from sklearn.model_selection import train_test_split\n",
    "from sklearn.preprocessing import MinMaxScaler\n",
    "from sklearn.metrics import mean_squared_error\n",
    "from keras.models import Sequential\n",
    "from keras.layers import Dense, Flatten, Dropout\n",
    "from keras.layers.convolutional import Conv1D, MaxPooling1D\n",
    "from bokeh.plotting import figure,output_file,show, output_notebook\n",
    "from bokeh.layouts import column\n",
    "from bokeh.models import Slider\n",
    "from bokeh.io import output_file, show\n",
    "from bokeh.models.widgets import FileInput\n",
    "\n",
    "\n",
    "\n",
    "n_sample = 1\n",
    "\n",
    "file_input = FileInput()\n",
    "# Load the data  \n",
    "frame = pd.read_csv('dataframe1.csv')\n",
    "# formated data\n",
    "data = np.hstack((frame.values.astype('float32')[:, :-2], frame.values.astype('float32')[:, [-2]]))\n",
    "\n",
    "# normalize data \n",
    "scaler = MinMaxScaler(feature_range=(0, 1))\n",
    "\n",
    "scaled = scaler.fit_transform(data)\n",
    "\n",
    "iput, oput = scaled[:,:-1], scaled[:,[-1]]\n",
    "\n",
    "# data split\n",
    "train_x, test_x, train_y, test_y = train_test_split(iput, oput, test_size=0.5, shuffle=True)\n",
    "\n",
    "# reshape data for model\n",
    "train_x = train_x.reshape(n_sample, len(train_x), iput.shape[1])\n",
    "test_x = test_x.reshape(n_sample, len(test_x), iput.shape[1])\n",
    "\n",
    "train_y = train_y.reshape(n_sample, 31912)\n",
    "test_y = test_y.reshape(n_sample, 31912)\n",
    "\n",
    "gc.collect()\n",
    "\n",
    "n_in, n_out, n_feature = train_x.shape[1], train_y.shape[1], train_x.shape[2]\n",
    "\n",
    "# training model\n",
    "model = Sequential()\n",
    "model.add(Conv1D(\n",
    "        filters=2,\n",
    "        kernel_size=7, \n",
    "        activation='relu', \n",
    "        input_shape=(n_in, n_feature)\n",
    "    )\n",
    ")\n",
    "model.add(MaxPooling1D(pool_size=2))\n",
    "model.add(Dropout(0.2)) #0.2 return better\n",
    "model.add(Flatten())\n",
    "model.add(Dense(64, activation='relu'))\n",
    "model.add(Dense(n_out))\n",
    "model.compile(optimizer='adam', loss='mae', metrics=['mse', 'mae'])\n",
    "\n",
    "\n",
    "#model.save_weights(str('depth_weight1.212')+'.h5')\n",
    "#model.load_weights('depth_weight1.253.h5')\n",
    "\n",
    "mdl = model.fit(\n",
    "        train_x, train_y, batch_size=32, validation_data=(test_x, test_y),\n",
    "        epochs=10, shuffle=False, verbose=2)\n",
    "\n",
    "output_notebook()\n",
    "\n",
    "output_file(\"stats.html\")\n",
    "\n",
    "TOOLTIPS = [\n",
    "    (\"index\", \"$index\"),\n",
    "    (\"(x,y)\", \"($x, $y)\"),\n",
    "    (\"desc\", \"@desc\"),\n",
    "]\n",
    "\n",
    "p = figure(tooltips=TOOLTIPS)\n",
    "\n",
    "p.line([1,2,3,4,5,6,7,8,9,10], mdl.history['loss'], line_color=\"blue\")\n",
    "p.line([1,2,3,4,5,6,7,8,9,10], mdl.history['val_loss'], line_color=\"red\")\n",
    "\n",
    "slider = Slider(start=0.1, end=2, step=0.01, value=0.2)\n",
    "\n",
    "\n",
    "\n",
    "show(column(p, slider, file_input))\n"
   ]
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "Python 3",
   "language": "python",
   "name": "python3"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.7.6"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 4
}
